apiVersion: v1
kind: Template
parameters:
  - name: SOURCE_REPOSITORY_URL
    description: The source URL for the application
    displayName: Source URL
    value: 'https://github.com/dummy_org/dummy_repo'
    required: true
  - name: GITHUB_WEBHOOK_SECRET
    description: The secret used to configure a GitHub webhook
    displayName: GitHub Webhook Secret
    required: true
    from: '[a-zA-Z0-9]{40}'
    generate: expression
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: profuse-meal-backend-database-bind
      labels:
        app: profuse-meal
    stringData:
      uri: profuse-meal-backend-database
      database: my_data
      user: dbuser
      password: secret
  - kind: ImageStreamTag
    apiVersion: v1
    metadata:
      name: 'profuse-meal-backend-database:10'
      creationTimestamp: null
      labels:
        app: profuse-meal
    tag:
      name: '10'
      annotations: null
      from:
        kind: DockerImage
        name: '172.30.1.1:5000/openshift/postgresql:10'
      generation: null
      importPolicy: {}
      referencePolicy:
        type: ''
    generation: 0
    lookupPolicy:
      local: false
    image:
      metadata:
        creationTimestamp: null
      dockerImageMetadata:
        kind: DockerImage
        apiVersion: '1.0'
        Id: ''
        Created: null
        ContainerConfig: {}
      dockerImageMetadataVersion: '1.0'
      dockerImageLayers: null
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: profuse-meal-backend-database
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      strategy:
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - profuse-meal-backend-database
            from:
              kind: ImageStreamTag
              namespace: openshift
              name: 'postgresql:10'
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: profuse-meal-backend-database
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: profuse-meal-backend-database
        spec:
          volumes:
            - name: profuse-meal-backend-database-volume-1
              emptyDir: {}
          containers:
            - name: profuse-meal-backend-database
              image: '172.30.1.1:5000/openshift/postgresql:10'
              ports:
                - containerPort: 5432
                  protocol: TCP
              resources:
                limits:
                  memory: 512Mi
              volumeMounts:
                - name: profuse-meal-backend-database-volume-1
                  mountPath: /var/lib/pgsql/data
              env:
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: database
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: user
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: password
              livenessProbe:
                initialDelaySeconds: 120
                exec:
                  command:
                    - /usr/libexec/check-container
                    - '--live'
              readinessProbe:
                initialDelaySeconds: 5
                exec:
                  command:
                    - /usr/libexec/check-container
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: profuse-meal-backend-database
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      ports:
        - name: 5432-tcp
          protocol: TCP
          port: 5432
          targetPort: 5432
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: profuse-meal-backend-database
    status:
      loadBalancer: {}
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: openjdk18-openshift
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      lookupPolicy:
        local: false
      tags:
        - name: latest
          from:
            kind: DockerImage
            name: registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift
          generation: null
          importPolicy: {}
          referencePolicy:
            type: ''
    status:
      dockerImageRepository: ''
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: profuse-meal-backend
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      lookupPolicy:
        local: false
    status:
      dockerImageRepository: ''
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: profuse-meal-backend
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      triggers:
        - type: GitHub
          github:
            secret: '${GITHUB_WEBHOOK_SECRET}'
        - type: ConfigChange
        - type: ImageChange
          imageChange: {}
      source:
        type: Git
        git:
          uri: '${SOURCE_REPOSITORY_URL}'
        contextDir: backend
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: 'openjdk18-openshift:latest'
          incremental: true
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: profuse-meal-backend-database-bind
                  key: uri
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: profuse-meal-backend-database-bind
                  key: user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: profuse-meal-backend-database-bind
                  key: password
      output:
        to:
          kind: ImageStreamTag
          name: 'profuse-meal-backend:latest'
      resources: {}
      postCommit: {}
      nodeSelector: null
    status:
      lastVersion: 0
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: profuse-meal-backend
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      strategy:
        resources: {}
      triggers:
        - type: ConfigChange
        - type: ImageChange
          imageChangeParams:
            automatic: true
            containerNames:
              - profuse-meal-backend
            from:
              kind: ImageStreamTag
              name: 'profuse-meal-backend:latest'
      replicas: 1
      test: false
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: profuse-meal-backend
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: placeholder-app-label-d46881878f594a2dadfd963843452aab
            deploymentconfig: profuse-meal-backend
        spec:
          containers:
            - name: profuse-meal-backend
              image: 'profuse-meal-backend:latest'
              ports:
                - containerPort: 8080
                  protocol: TCP
                - containerPort: 8443
                  protocol: TCP
                - containerPort: 8778
                  protocol: TCP
              resources:
                limits:
                  memory: 2G
              env:
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: uri
                - name: DB_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: profuse-meal-backend-database-bind
                      key: password
              readinessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                timeoutSeconds: 3
                periodSeconds: 10
                failureThreshold: 10
              livenessProbe:
                httpGet:
                  path: /health
                  port: 8080
                  scheme: HTTP
                initialDelaySeconds: 5
                timeoutSeconds: 3
    status:
      latestVersion: 0
      observedGeneration: 0
      replicas: 0
      updatedReplicas: 0
      availableReplicas: 0
      unavailableReplicas: 0
  - kind: Service
    apiVersion: v1
    metadata:
      name: profuse-meal-backend
      creationTimestamp: null
      labels:
        app: profuse-meal
    spec:
      ports:
        - name: 8080-tcp
          protocol: TCP
          port: 8080
          targetPort: 8080
        - name: 8443-tcp
          protocol: TCP
          port: 8443
          targetPort: 8443
        - name: 8778-tcp
          protocol: TCP
          port: 8778
          targetPort: 8778
      selector:
        app: placeholder-app-label-d46881878f594a2dadfd963843452aab
        deploymentconfig: profuse-meal-backend
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Route
    metadata:
      name: profuse-meal-backend
      labels:
        app: profuse-meal
    spec:
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: profuse-meal-backend
